/*
 * ===========================================================================
 * Exercise 13: DAG (Directed Acyclic Graph) Representation  --  C
 * ===========================================================================
 *
 * CONCEPT:
 *   A Directed Acyclic Graph (DAG) represents expressions so that identical
 *   subexpressions share a single node.  This eliminates redundant
 *   computation (common subexpression elimination, CSE).  Unlike a tree,
 *   where a+b computed twice yields two separate subtrees, a DAG merges
 *   them into one node.
 *
 * ALGORITHM:
 *   For each TAC statement  result = left op right:
 *     1. Find or create leaf nodes for `left` and `right`.
 *     2. Search existing interior nodes for one with the same (op, left, right).
 *        If found, reuse it (CSE).  Otherwise, create a new interior node.
 *     3. Attach `result` as a label on the (possibly shared) node.
 *   Optimised TAC is generated by emitting each interior node at most once
 *   in dependency order.
 *
 * TIME COMPLEXITY:  O(n^2) worst case for n statements (linear scan for
 *                   existing nodes).  O(n) with hashing.
 * SPACE COMPLEXITY: O(n) for DAG nodes and labels.
 *
 * EXAMPLE:
 *   Input:  t1=a+b, t2=a+b, t3=t1*t2, x=t3
 *   DAG:    a, b are leaves; one + node (labels t1,t2);
 *           one * node (labels t3,x) whose both children are the + node.
 *   Optimised:  t1 = a + b  /  t3 = t1 * t1  /  x = t3
 * ===========================================================================
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ---------- constants ----------------------------------------------------- */
#define MAX_NODES   128
#define MAX_LABELS    8
#define MAX_NAME     64
#define MAX_TAC      64
#define MAX_OPT_TAC  64

/* ---------- DAG node ------------------------------------------------------ */

typedef struct {
    int  id;
    int  is_leaf;
    char leaf_value[MAX_NAME];       /* for leaf nodes                       */
    char op;                         /* operator for interior nodes, or '\0' */
    int  left;                       /* child node index (-1 if none)        */
    int  right;                      /* child node index (-1 if none)        */
    char labels[MAX_LABELS][MAX_NAME];
    int  label_count;
} DAGNode;

/* ---------- DAG state ----------------------------------------------------- */

static DAGNode nodes[MAX_NODES];
static int     node_count = 0;

/* name -> node index mapping (simple linear search) */
typedef struct { char name[MAX_NAME]; int node_idx; } NameMap;
static NameMap name_map[MAX_NODES * 2];
static int     name_map_count = 0;

/* ---------- utility functions -------------------------------------------- */

static void dag_reset(void)
{
    node_count = 0;
    name_map_count = 0;
}

static int find_name(const char *name)
{
    for (int i = 0; i < name_map_count; i++)
        if (strcmp(name_map[i].name, name) == 0)
            return name_map[i].node_idx;
    return -1;
}

static void set_name(const char *name, int node_idx)
{
    /* Update existing entry if present */
    for (int i = 0; i < name_map_count; i++) {
        if (strcmp(name_map[i].name, name) == 0) {
            name_map[i].node_idx = node_idx;
            return;
        }
    }
    strncpy(name_map[name_map_count].name, name, MAX_NAME - 1);
    name_map[name_map_count].node_idx = node_idx;
    name_map_count++;
}

static int create_leaf(const char *value)
{
    int idx = node_count++;
    DAGNode *n = &nodes[idx];
    n->id = idx;
    n->is_leaf = 1;
    strncpy(n->leaf_value, value, MAX_NAME - 1);
    n->op = '\0';
    n->left = -1;
    n->right = -1;
    strncpy(n->labels[0], value, MAX_NAME - 1);
    n->label_count = 1;
    set_name(value, idx);
    return idx;
}

static int get_or_create_leaf(const char *name)
{
    int idx = find_name(name);
    if (idx >= 0) return idx;
    return create_leaf(name);
}

static void add_label(int node_idx, const char *label)
{
    DAGNode *n = &nodes[node_idx];
    if (n->label_count < MAX_LABELS) {
        strncpy(n->labels[n->label_count], label, MAX_NAME - 1);
        n->label_count++;
    }
    set_name(label, node_idx);
}

/* Search for an existing interior node with (op, left, right). */
static int find_existing(char op, int left, int right)
{
    for (int i = 0; i < node_count; i++) {
        if (!nodes[i].is_leaf &&
            nodes[i].op == op &&
            nodes[i].left == left &&
            nodes[i].right == right)
            return i;
    }
    return -1;
}

/* Create a new interior node. */
static int create_interior(char op, int left, int right, const char *label)
{
    int idx = node_count++;
    DAGNode *n = &nodes[idx];
    n->id = idx;
    n->is_leaf = 0;
    n->leaf_value[0] = '\0';
    n->op = op;
    n->left = left;
    n->right = right;
    strncpy(n->labels[0], label, MAX_NAME - 1);
    n->label_count = 1;
    set_name(label, idx);
    return idx;
}

/* ---------- build DAG from TAC ------------------------------------------- */

static void build_dag(const char **tac_lines, int tac_count_in)
{
    dag_reset();

    for (int i = 0; i < tac_count_in; i++) {
        char result[MAX_NAME], left[MAX_NAME], right[MAX_NAME];
        char op;
        int fields = sscanf(tac_lines[i], "%63s = %63s %c %63s",
                            result, left, &op, right);

        if (fields == 4) {
            /* Binary: result = left op right */
            int left_idx  = get_or_create_leaf(left);
            int right_idx = get_or_create_leaf(right);
            int existing  = find_existing(op, left_idx, right_idx);
            if (existing >= 0) {
                add_label(existing, result);
            } else {
                create_interior(op, left_idx, right_idx, result);
            }
        } else if (fields >= 2) {
            /* Copy: result = source */
            int src_idx = get_or_create_leaf(left);
            add_label(src_idx, result);
        }
    }
}

/* ---------- print DAG ---------------------------------------------------- */

static void print_dag(void)
{
    for (int i = 0; i < node_count; i++) {
        DAGNode *n = &nodes[i];
        if (n->is_leaf) {
            printf("    n%d: leaf  value=%-6s  labels=[", n->id, n->leaf_value);
        } else {
            printf("    n%d: '%c'   left=n%d  right=n%d  labels=[",
                   n->id, n->op, n->left, n->right);
        }
        for (int j = 0; j < n->label_count; j++) {
            if (j > 0) printf(", ");
            printf("%s", n->labels[j]);
        }
        printf("]\n");
    }
}

/* ---------- generate optimised TAC --------------------------------------- */

static int  is_temporary(const char *name);

static char opt_tac[MAX_OPT_TAC][128];
static int  opt_count = 0;
static int  emitted[MAX_NODES];

static void visit(int idx)
{
    if (idx < 0 || emitted[idx]) return;
    DAGNode *n = &nodes[idx];
    if (n->is_leaf) { emitted[idx] = 1; return; }

    visit(n->left);
    visit(n->right);
    emitted[idx] = 1;

    const char *left_name  = nodes[n->left].labels[0];
    const char *right_name = nodes[n->right].labels[0];
    snprintf(opt_tac[opt_count++], 128, "%s = %s %c %s",
             n->labels[0], left_name, n->op, right_name);
}

static int is_temporary(const char *name)
{
    if (name[0] != 't') return 0;
    for (int i = 1; name[i]; i++)
        if (name[i] < '0' || name[i] > '9') return 0;
    return (name[1] != '\0');
}

static void generate_optimised(void)
{
    opt_count = 0;
    memset(emitted, 0, sizeof(emitted));

    for (int i = 0; i < node_count; i++)
        if (!nodes[i].is_leaf)
            visit(i);

    /* Emit copy assignments for non-temporary aliases */
    for (int i = 0; i < node_count; i++) {
        DAGNode *n = &nodes[i];
        for (int j = 1; j < n->label_count; j++) {
            if (!is_temporary(n->labels[j])) {
                snprintf(opt_tac[opt_count++], 128, "%s = %s",
                         n->labels[j], n->labels[0]);
            }
        }
    }
}

/* ---------- driver ------------------------------------------------------- */

static void process_test_case(int case_num, const char *description,
                               const char **tac_lines, int tac_n)
{
    printf("  --- Test Case %d: %s ---\n", case_num, description);
    printf("  Input Three-Address Code:\n");
    for (int i = 0; i < tac_n; i++)
        printf("    %s\n", tac_lines[i]);
    printf("\n");

    build_dag(tac_lines, tac_n);

    printf("  DAG Nodes:\n");
    print_dag();
    printf("\n");

    generate_optimised();
    printf("  Optimised Three-Address Code:\n");
    for (int i = 0; i < opt_count; i++)
        printf("    %s\n", opt_tac[i]);
    printf("\n");
}

int main(void)
{
    printf("=================================================================\n");
    printf("   DAG (Directed Acyclic Graph) REPRESENTATION  --  C\n");
    printf("=================================================================\n\n");

    /* Test 1 */
    const char *tac1[] = { "t1 = a + b", "t2 = a + b",
                           "t3 = t1 * t2", "x = t3" };
    process_test_case(1, "Common subexpression a + b", tac1, 4);

    /* Test 2 */
    const char *tac2[] = { "t1 = a + b", "t2 = c + d",
                           "t3 = a + b", "t4 = c + d",
                           "t5 = t1 * t2", "t6 = t3 * t4",
                           "y = t5 + t6" };
    process_test_case(2, "Multiple common subexpressions", tac2, 7);

    /* Test 3 */
    const char *tac3[] = { "t1 = a + b", "t2 = c - d",
                           "t3 = t1 * t2", "z = t3" };
    process_test_case(3, "No common subexpressions", tac3, 4);

    /* Test 4 */
    const char *tac4[] = { "t1 = a + b", "t2 = a + b",
                           "t3 = t1 + t2", "t4 = t3 + t1",
                           "w = t4" };
    process_test_case(4, "Chained computation with reuse", tac4, 5);

    printf("=================================================================\n");
    printf("  All test cases processed successfully.\n");
    printf("=================================================================\n");
    return 0;
}
