"""
================================================================================
Exercise 13: DAG (Directed Acyclic Graph) Representation
================================================================================

CONCEPT:
    A Directed Acyclic Graph (DAG) is used in compilers to represent
    expressions in a way that automatically detects and eliminates common
    subexpressions.  Unlike an expression tree where identical subexpressions
    produce separate subtrees, a DAG shares a single node for every
    computation that has already been performed with the same operator and
    operands.

ALGORITHM:
    For each TAC statement  result = left op right:
      1. Look up (or create) the DAG node for `left` and `right`.
      2. Check whether a node with the same (operator, left_child, right_child)
         already exists.  If so, reuse it (common subexpression elimination).
         Otherwise, create a new interior node.
      3. Attach the variable name `result` as a label on the node.
    For simple copies (result = source), point `result` at the same node as
    `source`.

    After the DAG is built, optimised TAC is generated by a post-order
    traversal that emits each node at most once.

TIME COMPLEXITY:  O(n^2) in the worst case for n TAC statements (linear scan
                  to detect existing nodes).  Can be reduced to O(n) with
                  hashing.
SPACE COMPLEXITY: O(n) for DAG nodes.

EXAMPLE:
    Input TAC:                     DAG nodes:
      t1 = a + b                    n0: a
      t2 = a + b  (common!)        n1: b
      t3 = t1 * t2                 n2: + (n0, n1)  labels: {t1, t2}
      x  = t3                      n3: * (n2, n2)  labels: {t3, x}

    Optimised TAC:
      t1 = a + b
      t3 = t1 * t1
      x  = t3
================================================================================
"""


class DAGNode:
    """A node in the Directed Acyclic Graph."""

    def __init__(self, node_id, operator=None, left=None, right=None, leaf_value=None):
        self.node_id = node_id
        self.operator = operator       # None for leaf nodes
        self.left = left               # DAGNode reference
        self.right = right             # DAGNode reference
        self.leaf_value = leaf_value   # variable/constant name for leaf nodes
        self.labels = []               # variable names attached to this node

    def is_leaf(self):
        return self.operator is None

    def __repr__(self):
        if self.is_leaf():
            return f"n{self.node_id}: leaf({self.leaf_value}) labels={self.labels}"
        return (f"n{self.node_id}: {self.operator} "
                f"(n{self.left.node_id}, n{self.right.node_id}) "
                f"labels={self.labels}")


class DAGBuilder:
    """
    Builds a DAG from a sequence of three-address code statements,
    detecting and eliminating common subexpressions.
    """

    def __init__(self):
        self.nodes = []              # list of all DAGNode objects
        self.name_to_node = {}       # variable name -> DAGNode
        self.next_id = 0

    def _new_node(self, **kwargs):
        """Create and register a new DAG node."""
        node = DAGNode(node_id=self.next_id, **kwargs)
        self.next_id += 1
        self.nodes.append(node)
        return node

    def get_or_create_leaf(self, name):
        """Return the DAG node for a variable/constant, creating a leaf if needed."""
        if name in self.name_to_node:
            return self.name_to_node[name]
        node = self._new_node(leaf_value=name)
        node.labels.append(name)
        self.name_to_node[name] = node
        return node

    def find_existing(self, operator, left_node, right_node):
        """
        Search for an existing interior node with the same operator and children.
        Returns the node if found, None otherwise.
        """
        for node in self.nodes:
            if (not node.is_leaf()
                    and node.operator == operator
                    and node.left is left_node
                    and node.right is right_node):
                return node
        return None

    def add_statement(self, result, left, operator, right):
        """
        Process a binary TAC statement:  result = left op right.
        Reuses an existing node if the same computation was already recorded.
        """
        left_node = self.get_or_create_leaf(left)
        right_node = self.get_or_create_leaf(right)

        # Check for common subexpression
        existing = self.find_existing(operator, left_node, right_node)
        if existing is not None:
            # Reuse -- this is the CSE elimination
            existing.labels.append(result)
            self.name_to_node[result] = existing
            return existing

        # Create new interior node
        node = self._new_node(operator=operator, left=left_node, right=right_node)
        node.labels.append(result)
        self.name_to_node[result] = node
        return node

    def add_copy(self, result, source):
        """Process a simple copy:  result = source."""
        src_node = self.get_or_create_leaf(source)
        src_node.labels.append(result)
        self.name_to_node[result] = src_node
        return src_node

    def build_from_tac(self, tac_lines):
        """Parse and process a list of TAC strings."""
        self.nodes = []
        self.name_to_node = {}
        self.next_id = 0

        for line in tac_lines:
            parts = line.split()
            result = parts[0]
            left = parts[2]
            if len(parts) == 5:
                operator = parts[3]
                right = parts[4]
                self.add_statement(result, left, operator, right)
            else:
                self.add_copy(result, left)

    def print_dag(self):
        """Display the DAG nodes."""
        for node in self.nodes:
            if node.is_leaf():
                print(f"    n{node.node_id}: leaf  "
                      f"value={node.leaf_value:<6s}  labels={node.labels}")
            else:
                print(f"    n{node.node_id}: {node.operator:^3s}   "
                      f"left=n{node.left.node_id}  right=n{node.right.node_id}  "
                      f"labels={node.labels}")

    def generate_optimised_tac(self):
        """
        Produce optimised TAC by post-order traversal of the DAG.
        Each node is emitted at most once, using its first label as the
        representative variable name.
        """
        emitted = set()     # node ids already emitted
        output = []

        def visit(node):
            if node.node_id in emitted:
                return
            if node.is_leaf():
                emitted.add(node.node_id)
                return
            # Post-order: children first
            visit(node.left)
            visit(node.right)
            emitted.add(node.node_id)

            left_name = node.left.labels[0]
            right_name = node.right.labels[0]
            result_name = node.labels[0]
            output.append(f"{result_name} = {left_name} {node.operator} {right_name}")

        # Visit nodes that are roots or labelled with user variables
        # Process in order of creation to preserve dependencies
        for node in self.nodes:
            if not node.is_leaf():
                visit(node)

        # Also emit copy assignments for nodes with multiple labels where one
        # is a user variable (not a temporary)
        for node in self.nodes:
            if len(node.labels) > 1:
                primary = node.labels[0]
                for alias in node.labels[1:]:
                    # Only emit if alias is a user variable (not temp) and different
                    if not (alias[0] == 't' and alias[1:].isdigit()):
                        output.append(f"{alias} = {primary}")

        return output


def process_test_case(case_num, description, tac_lines):
    """Build a DAG from TAC, display it, and show optimised output."""
    print(f"  --- Test Case {case_num}: {description} ---")
    print("  Input Three-Address Code:")
    for line in tac_lines:
        print(f"    {line}")
    print()

    builder = DAGBuilder()
    builder.build_from_tac(tac_lines)

    print("  DAG Nodes:")
    builder.print_dag()
    print()

    optimised = builder.generate_optimised_tac()
    print("  Optimised Three-Address Code:")
    for line in optimised:
        print(f"    {line}")
    print()


def main():
    print("=" * 65)
    print("   DAG (Directed Acyclic Graph) REPRESENTATION")
    print("=" * 65)
    print()

    # Test case 1: Common subexpression a + b
    process_test_case(
        1,
        "Common subexpression a + b",
        [
            "t1 = a + b",
            "t2 = a + b",
            "t3 = t1 * t2",
            "x = t3",
        ],
    )

    # Test case 2: Multiple common subexpressions
    process_test_case(
        2,
        "Multiple common subexpressions",
        [
            "t1 = a + b",
            "t2 = c + d",
            "t3 = a + b",
            "t4 = c + d",
            "t5 = t1 * t2",
            "t6 = t3 * t4",
            "y = t5 + t6",
        ],
    )

    # Test case 3: No common subexpressions (all unique)
    process_test_case(
        3,
        "No common subexpressions",
        [
            "t1 = a + b",
            "t2 = c - d",
            "t3 = t1 * t2",
            "z = t3",
        ],
    )

    # Test case 4: Chain with reuse
    process_test_case(
        4,
        "Chained computation with reuse",
        [
            "t1 = a + b",
            "t2 = a + b",
            "t3 = t1 + t2",
            "t4 = t3 + t1",
            "w = t4",
        ],
    )

    print("=" * 65)
    print("  All test cases processed successfully.")
    print("=" * 65)


if __name__ == "__main__":
    main()
